from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
driver=webdriver.Chrome(executable_path="C:\\Users\\sinem.ulger\\Downloads\\chromedriver_win32\\chromedriver.exe")
driver.get('https://www.n11.com/')
time.sleep(2)
driver.implicitly_wait(10)
driver.find_element_by_xpath('//*[@id="userKvkkModal"]/div/div[2]/span').click()
driver.implicitly_wait(10)
giris_yap=driver.find_element_by_xpath('//*[@id="header"]/div/div/div[2]/div[2]/div[2]/div/div/a[1]').click()
time.sleep(2)
email_input=driver.find_element_by_id('email')
email_input.send_keys('sinemulger@gmail.com')
time.sleep(2)
password_input=driver.find_element_by_id('password')
password_input.send_keys('sinem123')
time.sleep(2)
driver.implicitly_wait(10)
driver.find_element_by_id('loginForm').submit()
time.sleep(2)
search_input=driver.find_element_by_id('searchData')
search_input.send_keys('samsung')
time.sleep(1)
driver.implicitly_wait(10)
driver.find_element_by_xpath('//*[@id="header"]/div/div/div[2]/div[1]/a/span').click()
time.sleep(5)
driver.quit()